-- -------------------------------------------------------- PROBLEM ----------------------------------------------------------------------------------------------------
-- Q4 is coming up and our ad spend is out of control. We want to send out a 30% discount code next week to boost revenue, but finance said we can't just blast the
-- whole email list again because it's killing our margins. Can you pull some data and tell us who we should actually email? I need a CSV of the target users by Friday

-- -------------------------------------------------------------------
-- PHASE 1 : Create Schema & Load Data( CSV ) into it
-- -------------------------------------------------------------------

CREATE TABLE raw_online_retail (
    InvoiceNo VARCHAR(20),
    StockCode VARCHAR(20),
    Description VARCHAR(255),
    Quantity INT,
    InvoiceDate VARCHAR(50), -- Import as string first to avoid date-format crashes
    UnitPrice DECIMAL(10, 4),
    CustomerID VARCHAR(20),
    Country VARCHAR(50)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/Online Retail.csv'
INTO TABLE raw_online_retail
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"' -- Handles descriptions that have commas inside them
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; -- Skips the header row 

describe raw_online_retail; -- check data types

select count(CustomerID) from raw_online_retail where CustomerID is null or CustomerID = ''; -- check null/empty values (135080 values are null/empty)
select count(CustomerID) from raw_online_retail where Quantity <=0; -- check negitive values
-- result: (In Quantity 10624 values are negative or equall to zero, In UnitPrice 2517 values are negative or equall to zero )

WITH 

-- -----------------------------------------------------------------------------
-- PHASE 2 : DATA CLEANING & FEATURE ENGINEERING
-- -----------------------------------------------------------------------------
CleanedData AS (
SELECT 
	TRIM(InvoiceNo) AS InvoiceNo ,
    TRIM(StockCode) AS StockCode,
    TRIM(Description) AS Description ,
    Quantity ,
    str_to_date(InvoiceDate,'%m/%d/%Y %H:%i') AS InvoiceDate,
    UnitPrice ,
    (UnitPrice * Quantity) AS Total_Value,
    TRIM(CustomerID) AS CustomerID,
    TRIM(Country) AS Country
FROM 
	raw_online_retail
WHERE 
	CustomerID IS NOT NULL -- FILTER OUT NULL VALUES
    AND CustomerID != ''   -- FLTER OUT EMPTY VALUES
    AND Quantity > 0 -- FLTER OUT return VALUES
    AND UnitPrice > 0 -- FLTER OUT errors/gifts
),

-- -----------------------------------------------------------------------------
-- PHASE 3: CALCULATE THE ANCHOR DATE
-- -----------------------------------------------------------------------------
GlobalAnchor AS (
    -- Get the maximum date in the dataset and add 1 day to prevent Recency = 0
   SELECT DATE_ADD(MAX(InvoiceDate),INTERVAL 1 DAY) AS anchor_date FROM CleanedData  
),

-- -----------------------------------------------------------------------------
-- PHASE 4 : CALCULATE CONTINUOUS R, F, M METRICS
-- -----------------------------------------------------------------------------
RFM_Base AS (
    SELECT 
        CustomerID,
        -- Recency: Days between their last purchase and the anchor date
        datediff((SELECT anchor_date FROM GlobalAnchor),max(InvoiceDate)) AS Recency ,
        
        -- Frequency: Count of unique transactions (not individual items)
        COUNT(DISTINCT InvoiceNo) AS Frequency ,
        
        -- Monetary: Sum of all revenue generated by this customer
        SUM(Total_Value) AS Monetary
    FROM CleanedData 
    GROUP BY CustomerID
),

-- -----------------------------------------------------------------------------
-- PHASE 5: ASSIGN QUANTILE SCORES (1-5) USING WINDOW FUNCTIONS
-- -----------------------------------------------------------------------------
RFM_Scores AS (
	SELECT 
		CustomerID,
        Recency,
        Frequency,
        Monetary,
        -- NTILE automatically splits the data into 5 equal buckets.
        -- Recency: Order DESC so worst (highest days) gets 1, best gets 5
        NTILE(5) OVER (ORDER BY Recency DESC) AS R_Score ,
        
        -- Frequency & Monetary: Order ASC so lowest gets 1, highest gets 5
		NTILE(5) OVER (ORDER BY Frequency ASC) AS F_Score,
        NTILE(5) OVER (ORDER BY Monetary ASC) AS M_Score
        
    FROM RFM_Base
)

-- -----------------------------------------------------------------------------
-- PHASE 6: HEURISTIC SEGMENTATION (THE BUSINESS LOGIC)
-- -----------------------------------------------------------------------------
SELECT 
    CustomerID,
    Recency,
    Frequency,
    Monetary,
    CONCAT(R_Score, F_Score, M_Score) AS RFM_Cohort,
    (R_Score + F_Score + M_Score) AS RFM_Composite,
    
    -- Assign business labels based on top-down heuristic rules
    CASE 
        -- 1. High Value / High Risk 
        WHEN R_Score = 1 AND F_Score in (4,5) AND M_Score in (4,5) THEN 'Can''t Lose Them'
        WHEN R_Score IN (1, 2) AND F_Score IN (4, 5) THEN 'At Risk'
        
        -- 2. The Core Engine
        WHEN R_Score IN (4, 5) AND F_Score IN (4, 5) THEN 'Champions'
        WHEN R_Score IN (3, 4, 5) AND F_Score IN (4, 5) THEN 'Loyalists'
        WHEN R_Score IN (4, 5) AND F_Score IN (2, 3) THEN 'Potential Loyalists'
        
        -- 3. New & Recent
        WHEN R_Score = 5 AND F_Score = 1 THEN 'Recent Customers'
        
        -- 4. The Churn
        WHEN R_Score IN (1, 2) AND F_Score IN (1, 2) THEN 'Hibernating'
        
        -- 5. The Catch-All
        ELSE 'Average / Needs Attention' 
    END AS Customer_Segment

FROM RFM_Scores
ORDER BY RFM_Composite DESC, Monetary DESC ; 

 